Repository xing/hops, pull requests merged in 2021-02, with the labels that each got.

#1504 chore: have Renovate set PR labels for base branch
  renovate.json
Labels: :package: master, :package: v12, :package: v13

#1532 chore: pin version of react-apollo in canarist runs
  package.json
  renovate.json
Labels: :package: v13

#1533 chore: have Renovate update pinned version of react-apollo
  renovate.json
Labels: :package: master

#1534 chore: add status placeholder for every required check
  bors.toml
Labels: :package: master, :package: v12, :package: v13

#1537 chore: configure renovate to create PRs against release-pr branches
  renovate.json
Labels: :package: master

#1545 docs: apollo documentation links
  packages/react-apollo/README.md
Labels: :package: v12, :package: v13

#1556 chore: automatically release nightly version from master
  .github/workflows/release.yml
  package.json
Labels: :package: master

#1557 chore: configure release bot as author for automatic releases
  .github/workflows/release.yml
Labels: :package: master

#1558 chore: use custom github token to push release notes
  .github/workflows/release.yml
Labels: :package: master

#1559 chore: add publish action to push tags and publish to registry
  .github/workflows/publish.yml
Labels: :package: master, :package: v12, :package: v13, Merging… :robot:

#1560 Revert nightly releases on master
  .github/workflows/release.yml
Labels: :package: master

#1561 chore: add release preparation command
  .github/release-bot.yml
  package.json
Labels: :package: master, :package: v12, :package: v13

#1564 chore: fix prepare release command
  package.json
Labels: :package: master, :package: v12, :package: v13, Merging… :robot:

#1567 chore: revert "chore: release v12.5.9"
  CHANGELOG.md
  lerna.json
  packages/apollo-mock-server/CHANGELOG.md
  packages/apollo-mock-server/package.json
  packages/bootstrap/CHANGELOG.md
  packages/bootstrap/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/create-hops-app/CHANGELOG.md
  packages/create-hops-app/package.json
  packages/development-proxy/CHANGELOG.md
  packages/development-proxy/package.json
  packages/express/CHANGELOG.md
  packages/express/package.json
  packages/graphql/CHANGELOG.md
  packages/graphql/package.json
  packages/hops/CHANGELOG.md
  packages/hops/package.json
  packages/info/CHANGELOG.md
  packages/info/package.json
  packages/jest-preset/CHANGELOG.md
  packages/jest-preset/package.json
  packages/lambda/CHANGELOG.md
  packages/lambda/package.json
  packages/mixin/CHANGELOG.md
  packages/mixin/package.json
  packages/postcss/CHANGELOG.md
  packages/postcss/package.json
  packages/pwa/CHANGELOG.md
  packages/pwa/package.json
  packages/react-apollo/CHANGELOG.md
  packages/react-apollo/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/redux/CHANGELOG.md
  packages/redux/package.json
  packages/spec/CHANGELOG.md
  packages/spec/package.json
  packages/styled-components/CHANGELOG.md
  packages/styled-components/package.json
  packages/template-graphql/CHANGELOG.md
  packages/template-graphql/package.json
  packages/template-react/CHANGELOG.md
  packages/template-react/package.json
  packages/template-redux/CHANGELOG.md
  packages/template-redux/package.json
  packages/typescript/CHANGELOG.md
  packages/typescript/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  packages/yargs/CHANGELOG.md
  packages/yargs/package.json
Labels: :package: v12, Merging… :robot:

#1569 chore: fix changelog creation in publish action
  .github/workflows/publish.yml
Labels: :package: master, :package: v12, :package: v13, Merging… :robot:

#1574 chore: install & cache Node dependencies in Publish Action
  .github/workflows/publish.yml
Labels: :package: master, :package: v12, :package: v13

#1573 chore: revert "chore: release v13.3.3"
  CHANGELOG.md
  lerna.json
  packages/apollo-mock-server/CHANGELOG.md
  packages/apollo-mock-server/package.json
  packages/bootstrap/CHANGELOG.md
  packages/bootstrap/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/create-hops-app/CHANGELOG.md
  packages/create-hops-app/package.json
  packages/development-proxy/CHANGELOG.md
  packages/development-proxy/package.json
  packages/express/CHANGELOG.md
  packages/express/package.json
  packages/graphql/CHANGELOG.md
  packages/graphql/package.json
  packages/hops/CHANGELOG.md
  packages/hops/package.json
  packages/info/CHANGELOG.md
  packages/info/package.json
  packages/jest-environment/CHANGELOG.md
  packages/jest-environment/package.json
  packages/jest-preset/CHANGELOG.md
  packages/jest-preset/package.json
  packages/lambda/CHANGELOG.md
  packages/lambda/package.json
  packages/mixin/CHANGELOG.md
  packages/mixin/package.json
  packages/postcss/CHANGELOG.md
  packages/postcss/package.json
  packages/pwa/CHANGELOG.md
  packages/pwa/package.json
  packages/react-apollo/CHANGELOG.md
  packages/react-apollo/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/redux/CHANGELOG.md
  packages/redux/package.json
  packages/spec/CHANGELOG.md
  packages/spec/package.json
  packages/styled-components/CHANGELOG.md
  packages/styled-components/package.json
  packages/template-graphql/CHANGELOG.md
  packages/template-graphql/package.json
  packages/template-react/CHANGELOG.md
  packages/template-react/package.json
  packages/template-redux/CHANGELOG.md
  packages/template-redux/package.json
  packages/typescript/CHANGELOG.md
  packages/typescript/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  packages/yargs/CHANGELOG.md
  packages/yargs/package.json
Labels: :package: v13

#1577 chore: revert "chore: release v13.3.3"
  CHANGELOG.md
  lerna.json
  packages/apollo-mock-server/CHANGELOG.md
  packages/apollo-mock-server/package.json
  packages/bootstrap/CHANGELOG.md
  packages/bootstrap/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/create-hops-app/CHANGELOG.md
  packages/create-hops-app/package.json
  packages/development-proxy/CHANGELOG.md
  packages/development-proxy/package.json
  packages/express/CHANGELOG.md
  packages/express/package.json
  packages/graphql/CHANGELOG.md
  packages/graphql/package.json
  packages/hops/CHANGELOG.md
  packages/hops/package.json
  packages/info/CHANGELOG.md
  packages/info/package.json
  packages/jest-environment/CHANGELOG.md
  packages/jest-environment/package.json
  packages/jest-preset/CHANGELOG.md
  packages/jest-preset/package.json
  packages/lambda/CHANGELOG.md
  packages/lambda/package.json
  packages/mixin/CHANGELOG.md
  packages/mixin/package.json
  packages/postcss/CHANGELOG.md
  packages/postcss/package.json
  packages/pwa/CHANGELOG.md
  packages/pwa/package.json
  packages/react-apollo/CHANGELOG.md
  packages/react-apollo/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/redux/CHANGELOG.md
  packages/redux/package.json
  packages/spec/CHANGELOG.md
  packages/spec/package.json
  packages/styled-components/CHANGELOG.md
  packages/styled-components/package.json
  packages/template-graphql/CHANGELOG.md
  packages/template-graphql/package.json
  packages/template-react/CHANGELOG.md
  packages/template-react/package.json
  packages/template-redux/CHANGELOG.md
  packages/template-redux/package.json
  packages/typescript/CHANGELOG.md
  packages/typescript/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  packages/yargs/CHANGELOG.md
  packages/yargs/package.json
Labels: :package: v13

#1576 chore: fix retrieving the latest change on the CHANGELOG
  .github/workflows/publish.yml
Labels: :package: master, :package: v12, :package: v13

#1581 chore: fetch more commits, so we are able to get the correct diff
  .github/workflows/publish.yml
Labels: :package: master, :package: v12, :package: v13

#1582 chore: set correct npm release tag
  lerna.json
Labels: :package: v12

#1587 chore: have canarist test against internal release PR branch
  package.json
Labels: :package: v13

#1586 chore: have canarist test against internal release PR branch
  package.json
Labels: :package: v12

#1603 chore: remove foosbyte/kicker-trainer from canarist tests
  .github/workflows/node-ci.yml
  bors.toml
  package.json
Labels: :package: master, :package: v12, :package: v13

#1600 chore: check out release commit before publishing
  .github/workflows/publish.yml
Labels: :package: master, :package: v12, :package: v13

#1607 chore: revert "chore: release v13.3.4"
  CHANGELOG.md
  lerna.json
  packages/apollo-mock-server/CHANGELOG.md
  packages/apollo-mock-server/package.json
  packages/bootstrap/CHANGELOG.md
  packages/bootstrap/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/create-hops-app/CHANGELOG.md
  packages/create-hops-app/package.json
  packages/development-proxy/CHANGELOG.md
  packages/development-proxy/package.json
  packages/express/CHANGELOG.md
  packages/express/package.json
  packages/graphql/CHANGELOG.md
  packages/graphql/package.json
  packages/hops/CHANGELOG.md
  packages/hops/package.json
  packages/info/CHANGELOG.md
  packages/info/package.json
  packages/jest-environment/CHANGELOG.md
  packages/jest-environment/package.json
  packages/jest-preset/CHANGELOG.md
  packages/jest-preset/package.json
  packages/lambda/CHANGELOG.md
  packages/lambda/package.json
  packages/mixin/CHANGELOG.md
  packages/mixin/package.json
  packages/postcss/CHANGELOG.md
  packages/postcss/package.json
  packages/pwa/CHANGELOG.md
  packages/pwa/package.json
  packages/react-apollo/CHANGELOG.md
  packages/react-apollo/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/redux/CHANGELOG.md
  packages/redux/package.json
  packages/spec/CHANGELOG.md
  packages/spec/package.json
  packages/styled-components/CHANGELOG.md
  packages/styled-components/package.json
  packages/template-graphql/CHANGELOG.md
  packages/template-graphql/package.json
  packages/template-react/CHANGELOG.md
  packages/template-react/package.json
  packages/template-redux/CHANGELOG.md
  packages/template-redux/package.json
  packages/typescript/CHANGELOG.md
  packages/typescript/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  packages/yargs/CHANGELOG.md
  packages/yargs/package.json
Labels: :package: v13

#1608 chore: write npm token into .npmrc
  .github/workflows/publish.yml
Labels: :package: master, :package: v12, :package: v13

#1612 Revert "chore: release v13.3.4"
  CHANGELOG.md
  lerna.json
  packages/apollo-mock-server/CHANGELOG.md
  packages/apollo-mock-server/package.json
  packages/bootstrap/CHANGELOG.md
  packages/bootstrap/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/create-hops-app/CHANGELOG.md
  packages/create-hops-app/package.json
  packages/development-proxy/CHANGELOG.md
  packages/development-proxy/package.json
  packages/express/CHANGELOG.md
  packages/express/package.json
  packages/graphql/CHANGELOG.md
  packages/graphql/package.json
  packages/hops/CHANGELOG.md
  packages/hops/package.json
  packages/info/CHANGELOG.md
  packages/info/package.json
  packages/jest-environment/CHANGELOG.md
  packages/jest-environment/package.json
  packages/jest-preset/CHANGELOG.md
  packages/jest-preset/package.json
  packages/lambda/CHANGELOG.md
  packages/lambda/package.json
  packages/mixin/CHANGELOG.md
  packages/mixin/package.json
  packages/postcss/CHANGELOG.md
  packages/postcss/package.json
  packages/pwa/CHANGELOG.md
  packages/pwa/package.json
  packages/react-apollo/CHANGELOG.md
  packages/react-apollo/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/redux/CHANGELOG.md
  packages/redux/package.json
  packages/spec/CHANGELOG.md
  packages/spec/package.json
  packages/styled-components/CHANGELOG.md
  packages/styled-components/package.json
  packages/template-graphql/CHANGELOG.md
  packages/template-graphql/package.json
  packages/template-react/CHANGELOG.md
  packages/template-react/package.json
  packages/template-redux/CHANGELOG.md
  packages/template-redux/package.json
  packages/typescript/CHANGELOG.md
  packages/typescript/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  packages/yargs/CHANGELOG.md
  packages/yargs/package.json
Labels: :package: v13

#1616 chore: use GH_TOKEN to push tags and releases
  .github/workflows/publish.yml
Labels: :package: master, :package: v12, :package: v13

#1618 Revert "chore: release v13.3.4"
  CHANGELOG.md
  lerna.json
  packages/apollo-mock-server/CHANGELOG.md
  packages/apollo-mock-server/package.json
  packages/bootstrap/CHANGELOG.md
  packages/bootstrap/package.json
  packages/config/CHANGELOG.md
  packages/config/package.json
  packages/create-hops-app/CHANGELOG.md
  packages/create-hops-app/package.json
  packages/development-proxy/CHANGELOG.md
  packages/development-proxy/package.json
  packages/express/CHANGELOG.md
  packages/express/package.json
  packages/graphql/CHANGELOG.md
  packages/graphql/package.json
  packages/hops/CHANGELOG.md
  packages/hops/package.json
  packages/info/CHANGELOG.md
  packages/info/package.json
  packages/jest-environment/CHANGELOG.md
  packages/jest-environment/package.json
  packages/jest-preset/CHANGELOG.md
  packages/jest-preset/package.json
  packages/lambda/CHANGELOG.md
  packages/lambda/package.json
  packages/mixin/CHANGELOG.md
  packages/mixin/package.json
  packages/postcss/CHANGELOG.md
  packages/postcss/package.json
  packages/pwa/CHANGELOG.md
  packages/pwa/package.json
  packages/react-apollo/CHANGELOG.md
  packages/react-apollo/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
  packages/redux/CHANGELOG.md
  packages/redux/package.json
  packages/spec/CHANGELOG.md
  packages/spec/package.json
  packages/styled-components/CHANGELOG.md
  packages/styled-components/package.json
  packages/template-graphql/CHANGELOG.md
  packages/template-graphql/package.json
  packages/template-react/CHANGELOG.md
  packages/template-react/package.json
  packages/template-redux/CHANGELOG.md
  packages/template-redux/package.json
  packages/typescript/CHANGELOG.md
  packages/typescript/package.json
  packages/webpack/CHANGELOG.md
  packages/webpack/package.json
  packages/yargs/CHANGELOG.md
  packages/yargs/package.json
Labels: :package: v13

#1617 chore: write npm token directly into .npmrc file
  .github/workflows/publish.yml
Labels: :package: master, :package: v12, :package: v13

#1624 chore: use action for deleting branches of closed PRs
  .github/workflows/delete-merged-branches.yml
Labels: :package: master

#1625 chore: do not verify npm access before publishing
  .github/workflows/publish.yml
Labels: :package: master, :package: v12, :package: v13

#1633 chore: prevent bors-bot from deleting branches
  bors.toml
Labels: :package: master, :package: v12, :package: v13
